name: Deploy Sentiment API to Azure

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  build-and-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to Azure Container Registry (ACR)
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.AZURE_ACR_NAME }}.azurecr.io
        username: ${{ secrets.AZURE_ACR_USERNAME }}
        password: ${{ secrets.AZURE_ACR_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/sentiment-api:${{ github.sha }} .
        docker push ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/sentiment-api:${{ github.sha }}

    - name: Wait for image to propagate
      run: sleep 40
      
    - name: Deploy to Azure Container App
      run: |
          az containerapp update \
          --name web-api-sentiment \
          --resource-group Openclassroom \
          --image ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/sentiment-api:${{ github.sha }} 

