name: Deploy Sentiment API to Azure

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Container Apps
      run: |
        az config set extension.use_dynamic_install=yes_without_prompt
        
        az containerapp up \
          --name web-api-sentiment \
          --resource-group Openclassroom \
          --location francecentral \
          --ingress external \
          --target-port 8000 \
          --source .

